### ISSUE TITLE
Upgrading from sass-rails 4.0.5 to sass-rails 5.0.0 breaks images

### ISSUE THREAD

**Issue by wallerjake** [joliss/jquery-ui-rails#89] opened 2014-12-17 22:27 UTC
The images found https://github.com/joliss/jquery-ui-rails/blob/master/app/assets/stylesheets/jquery-ui/theme.css.erb here are breaking when upgrading to the latest version of sass-rails.

This is happening when the assets are being compiled and digest is turned on. After the assets are compiled the css is still looking for the non digest images. This is incorrect. Reverting back to sass-rails 4.0.5 fixes this issues and the urls being references are referencing the correct digest URL.

Is this issue for jquery-ui-rails and can be fixed? Should I post the same question to the sass-rails gem?

**Comment by gbenedict** [comment] 2015-01-19 20:23
I was able to solve this by including core and theme explicitly:

```
@import "jquery-ui/core";
@import "jquery-ui/datepicker";
@import "jquery-ui/theme";
```

**Comment by ryanhattam** [comment] 2015-01-22 02:49
@gbenedict Good tip!

@import "jquery-ui/core";
@import "jquery-ui/theme";

Worked for me after upgrading to sass-rails 5.0.1.

**Comment by joliss** [comment] 2015-01-23 14:29
I'm not sure what's going on (and don't have super much time to debug this right now), but perhaps @josh or @rafaelfranca from sass-rails have a clue?

**Comment by josh** [comment] 2015-01-23 18:16
From the previously reported issue, it sounds like a case of mixing `@import` and `//= require`. Definitely only use one or the other. And since this library is just css, maybe only recommend a single `//= require jquery-ui`. The current readme already says that.

**Comment by tf** [comment] 2015-02-05 18:48
This makes the gem practically unusable for engines that are built using SASS. Our engine includes an scss file which provides mixins for the main app's `application.css`. Now we can no longer import `jquery-ui-rail` since it uses sprockets require...

**Comment by MrHubble** [comment] 2015-03-04 08:16
Thank you @gbenedict . I had the same problem and your solution worked for me also.

**Comment by floydj** [comment] 2015-03-18 12:43
FWIW, after upgrade to sass-rails, I had to change this in my application.scss file:

```scss
@import "jquery-ui";
```

To this (thanks @gbenedict!):

```scss
@import "jquery-ui/core";
@import "jquery-ui/datepicker";
@import "jquery-ui/theme";
```

**Comment by TechRsch** [comment] 2015-07-11 16:44
Actually, the following is required for current versions:
````
    @import 'jquery-ui/core.css';
    @import 'jquery-ui/datepicker.css';
    @import 'jquery-ui/theme.css';
````

**Comment by jgrannas** [comment] 2015-07-31 18:25
@TechRsch --- that worked for me! thanks

**Comment by rosenfeld** [comment] 2015-09-01 19:49
If I understood this issue correctly, it seems the problem is that some people want to `@import` the CSS for integrating with SASS while this gem doesn't support SASS integration through `@import "jquery-ui"` because jquery-ui-rails opted for supporting sprockets directives insteads. There are work-arounds though, like the ones reported in this thread.

Another possible solution would be to have some jquery-ui-sass.css file that would work by using `@import` instead of the sprockets requires, but I'm not sure @joliss would accept a pull request adding the extra files to support SASS out of the box. If she does, than I think someone willing to work on that should create a PR in another ticket. So, I'm closing this one. If you think this issue should remain open, please tell us the reason and I may reopen it.

**Closed by rosenfeld** 2015-09-01 19:49 UTC
