### ISSUE TITLE
Update don t work

### ISSUE THREAD

**Issue by bobysess** [joliss/jquery-ui-rails#77] opened 2014-08-01 11:00 UTC
Hallo ,
i have   Jquery-ui-rails  version 4.0.5 installed  and   when i run 
bundle   update  jquery-ui-rails  
it  remains  the  version   4.1.1

**Comment by rosenfeld** [comment] 2015-09-01 19:38
I'm closing since we can't reproduce. Please let us know if you have more information on how to reproduce this and I'll reopen the ticket.

**Closed by rosenfeld** 2015-09-01 19:38 UTC
