### ISSUE TITLE
IE8: Forced scroll/jump to top of page on clicking on select menu

### ISSUE THREAD

**Issue by TimurNurislamov** [joliss/jquery-ui-rails#98] opened 2015-08-18 12:33 UTC
In IE8, clicking on any select/dropdown menu causes the page to scroll/jump to the top of the page.
```
gem 'jquery-ui-rails', '5.0.5'
```

**Comment by rosenfeld** [comment] 2015-08-18 12:49
Could you please create a sample application demonstrating the problem and a js-fiddle using the same jQuery UI version from the official source that works properly?

**Comment by TimurNurislamov** [comment] 2015-08-18 14:26
@rosenfeld 

JQuery UI 1.11.4 https://jsfiddle.net/kkho6xw0/
JQuery UI 1.11.1 https://jsfiddle.net/hc63bjy8/

Looks like jsfiddle not support IE8.

**Comment by rosenfeld** [comment] 2015-08-18 14:51
You can use jsbin:

https://jsbin.com/riheyaceho/edit?html,js,output

The output-ony URL runs great on IE8 for example:

https://jsbin.com/riheyaceho

Anyway, your JS code had a bug anyway `$(select)` should be `$('select')` for example.

Also, I asked for a sample application demonstrating that the bug only happens with jquery-ui-rails and not with regular jQuery UI in jsbin. You need to demonstrate the problem by allowing the page to scroll so that we could reproduce it. Your examples should work fine in jsbin and do not work using this gem for us to take a look at it.

**Comment by TimurNurislamov** [comment] 2015-08-18 15:12
@rosenfeld I've updated a comment above. Please take a look.

**Comment by rosenfeld** [comment] 2015-08-18 15:29
I could confirm this behavior but even though I can't explain you why it happens I can tell you this has nothing to do with this gem. Use this in a view and render this view without any layouts:

```html
<!DOCTYPE html>
<html>
<head>
  <%#= stylesheet_link_tag 'jquery-ui', debug: false %>
  <%#= javascript_include_tag 'jquery', debug: false %>
  <%#= javascript_include_tag 'jquery-ui', debug: false %>
  <link href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="https://code.jquery.com/jquery-1.11.3.js"></script>
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
  <meta charset="utf-8">
  <title>Test</title>

<style id="jsbin-css">
body {
  height: 1000px;
  padding-top: 300px;
}

select {
  width: 200px;
}
</style>
</head>
<body>
  <select>
    <option></option>
    <option>item</option>
    <option>item</option>
  </select>
<script>
$('select').selectmenu();
</script>

</body>
</html>
```

You should notice the bug still happens even though this gem is not being used. Now, if you save this page offline and load it again in IE8 it will work correctly. I have no idea why that happens, but I don't think this is related to this gem in any way.

I'm closing this ticket because it's not related to this gem but feel free to ask me to re-open it if you still think this only happens when this gem is present by demonstrating a sample Rails application without this gem that works fine in IE8.

**Closed by rosenfeld** 2015-08-18 15:29 UTC

**Comment by dankohn** [comment] 2015-08-18 15:53
I just wanted to say thanks to @rosenfeld for reviewing this. We'll pursue upstream with JQuery UI and add a link to that bug here for future reference.

**Comment by dankohn** [comment] 2015-08-19 23:23
FYI, this issue has been reported upstream here: http://bugs.jqueryui.com/ticket/14180

**Comment by rosenfeld** [comment] 2015-08-20 00:41
Congratulations! You did a great job with your investigation! 😀 well done!
