### ISSUE TITLE
`link_to 'text', resource, method: :delete` doesn't work any more

### ISSUE THREAD

**Issue by eugenk** [joliss/jquery-ui-rails#79] opened 2014-09-02 16:05 UTC
Since jquery-ui-rails 5.0.0
```ruby
link_to 'text', resource, method: :delete
```
doesn't create a link with the (http) DELETE method, but with the GET method. Hence, it's not possible to create a link to destroy an object with `link_to`. It only works with `button_to` right now.

With jquery-ui-rails 4.2.1 it still worked with `link_to`.

**Comment by mikeymicrophone** [comment] 2015-04-29 16:17
Even if this is actually an issue with jQuery, this library would be the one responsible for addressing it, since this is the one meant to be compatible with Rails.  Correct?

**Comment by rosenfeld** [comment] 2015-09-01 19:59
Hi @SGraef, looking at the mentioned ontohub issue it seems the problem is not related to jquery-ui-rails. Take a look at this particular line:

https://github.com/ontohub/ontohub/pull/1026/files#diff-a9c3bd311eab80c9ebe6a69830f9ad02R9

This line was added back in the commit and is not related to this gem:

``` javascript
//= require jquery_ujs
```

I'm closing this ticket because I think this is related to jquery_ujs being removed on the commit that introduced the bug. If this is not the case, please let us know and I'll reopen this ticket.

**Closed by rosenfeld** 2015-09-01 19:59 UTC
